### PR TITLE
fix prettier

### PR DESCRIPTION
**Pull request by peterjah**

### CODE REVIEW

**Review by Thykof — APPROVED** [review]
LGTM

**Comment by Thykof** [comment]
@peterjah what does this PR fixes?

**Comment by peterjah** [comment]
> @peterjah what does this PR fixes?

It fixes the config of as-prettier which was prettifying 0 files.
It also adds linting of typescript files and json

**Review by gregLibert — APPROVED** [review]
:man_shrugging: LGTM

**Pull request merged**
