### PR TITLE
add is final arg

### PR DESCRIPTION
**Pull request by Thykof**
I would like to get event quicker, so I want to be able to get pending events from the deployer.

### CODE REVIEW

**Review by gregLibert — APPROVED** [review]
:man_shrugging: LGTM

**Review by SebastienValla — APPROVED** [review]
LGTM !

**Comment by Thykof** [comment]
It does not work as I expect, I make it a draft for the moment.

**Comment by SlnPons** [comment]
This issue is blocked for more than a month now. Should we remove it from the board as no one is actively working on it or trying to unblock it?

**Comment by Thykof** [comment]
> This issue is blocked for more than a month now. Should we remove it from the board as no one is actively working on it or trying to unblock it?

let's close this PR because it was unfinished and the needs might have evolved or answered by following work

**Pull request closed without merging**
