### PR TITLE
Feature(proto-cli): added test for protobuf helper

### PR DESCRIPTION
**Pull request by 0xSwapFeeder**

### CODE REVIEW

**Comment by bilboquet** [comment]
same as the other PR:
please fix the CI and wait a bit for @Ben-Rey

**Review by bilboquet — APPROVED** [review]

**Comment by Ben-Rey** [comment]
Waiting CI to be fixed

**Comment by Ben-Rey** [comment]
@0xSwapFeeder

**Comment by Ben-Rey** [comment]
Outdated

**Pull request closed without merging**
